### ISSUE TITLE
session token with login

### ISSUE THREAD

**Issue by Ooggle** [MeatReed/NSModding#1]
login :
![image](https://user-images.githubusercontent.com/33269056/75615814-25044b00-5b49-11ea-9a0c-2f7ce7fb4e85.png)

**Comment by MeatReed** [comment]
T'es chiant la vérité

**Comment by MeatReed** [comment]
https://github.com/MeatReed/NSMultiTools/commit/903301258a5ccce51cd49c8014d6ad0237197880

**Comment by Ooggle** [comment]
ahah y'a pas de quoi
